version: '3'

services:
  ledfx:
    image: shirom/ledfx 
    container_name: ledfx
    environment: 
      - HOST=127.0.0.1
      - FORMAT=-r 44100 -f S16_LE -c 2
      - SQUEEZE=0
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - /dev/snd:/dev/snd
    ports:
      - 84:8888
    command: --user-profiles /profiles --profile de
    volumes:
      - ~/ledfx-config:/app/ledfx-config
      - ~/audio:/app/audio
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    group_add:
      - audio